---

# tasks file for ansible-dockerized-wordpress
- name: tasks
  hosts: local
  user: ubuntu
  become: true
  tasks:

  - name: "Launch database container"
    docker:
      name: db
      image: mariadb
      env:
        MYSQL_ROOT_PASSWORD: example

  - name: "Launch wordpress container"
    docker:
      name: wordpres
      image: wordpress
      links:
      - db:mysql
      ports:
      - 8080:80

